Add friends likes
setNewPassword/java-filmorate pull request #2
Opened 2023-04-06 10:02 UTC by dima-irqtsk

2023-04-06 20:32 UTC, ohelly requested changes
Привет! Отличная работа, прекрасный код! Есть одно небольшое замечание, а также ряд рекомендаций, на которые стоит обратить внимание. Жду исправлений!

2023-04-06 20:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public InMemoryFilmStorage() {
Рекомендация: В данном случае от конструктора можно избавиться и инициализировать поле сразу при объявлении. Конструкторы обычно создают в том случае, если в него приходят какие то параметры, например если бы в него приходила мапа со стартовым набором фильмов.
Аналогично для InMemoryUserStorage

2023-04-06 20:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +    private static Long idCounter = 0L;
Рекомендация: Работу с idCounter лучше вынести в хранилище, так как это его логика. Например, когда будете использовать уже БД, идентификаторы будут задаваться ею автоматически.
Соответсвенно тогда придется добавить новый метод в хранилище - обновление, а создание немного переделать.
Аналогично для UserService.

2023-04-06 20:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +    private UserStorage userRepository;
Необходимо исправить: Обычно сервис взаимодействует только со "своим" хранилищем, доступ к другим хранилищам осуществляется через их сервисы. Вместо UserStorage лучше использвать UserService.

2023-04-06 20:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
>          } else {
Рекомендация: В данном случае, вместо проверки и выкидывания исключения, можно испоьзовать уже готовый метод:
![image](https://user-images.githubusercontent.com/51891976/230487329-3f63b372-4d93-456c-9dc1-5a2bad605d15.png)

2023-04-06 20:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        likedFilm.getLikes().add(userRepository
Рекомендация: Если использовать UserService вместо UserStorage, то тогда будет лучше использовать уже готовый метод getUserById

2023-04-06 20:32 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
>      public User update(User user) {
Рекомендация: В данном случае также можно использовать уже готовый метод getUserFromRepositoryOrThrowException

2023-04-07 05:45 UTC, dima-irqtsk commented
Влад, спасибо за ревью, все правки внес.

2023-04-07 09:24 UTC, ohelly approved these changes
Привет! Все супер, все замечания исправлены. Работу принимаю, удачи в дальнейшем обучении!

2023-04-07 09:24 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
>          log.info("Добавлен новый фильм: {}", film);
Рекомендация: Не заметил в прошлый раз, лог лучше выводить непосредственно после операции добавления, иначе при добавлении может произойти ошибка, но лог при этом напишет, что фильм добавлен

2023-04-08 06:56 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
>          log.info("Добавлен новый фильм: {}", film);
Дельное замечание, спасибо.
Исправил и для юзера и для фильма.

2023-04-08 06:57 UTC, merged