Add database
setNewPassword/java-filmorate pull request #4
Opened 2023-05-08 07:53 UTC by dima-irqtsk

2023-05-08 18:02 UTC, ohelly requested changes
Привет! Отличная работа, все сделано круто! Оставил несколько рекомендаций, которые также, выполнять необязательно, на свое усмотрение.

2023-05-08 18:02 UTC, ohelly commented on src/main/resources/schema.sql
> +CREATE INDEX IF NOT EXISTS film_name_index ON films (name);
Отлично! Используются индексы

2023-05-08 18:02 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/UserDbStorage.java
> +    public UserDbStorage(JdbcTemplate jdbcTemplate) {
Рекомендация: Можно использовать аннотацию ломбока ``@RequiredArgsConstructor``, которая генерирует конструктор для всех final полей.

2023-05-08 18:02 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/UserDbStorage.java
> +    public boolean existsById(long id) {
Рекомендация: Вместо данного метода можно использовать метод getById и отталкиваться уж от Optional, который он возвращает

2023-05-08 18:02 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    public UserServiceImpl(@Qualifier("userDbStorage") UserStorage userStorage, FriendshipStorage friendshipStorage) {
Рекомендация: Здесь тоже можно использовать аннотацию ``@RequiredArgsConstructor``, а чтобы ломбок применил аннотацию Qualifier то к нему в конфиг нужно добавить строку:
![image](https://user-images.githubusercontent.com/51891976/236894050-6731c8d0-ff62-4e7e-a6b0-eb33ec20553c.png)
![image](https://user-images.githubusercontent.com/51891976/236894113-9d948ed5-4a63-404b-b3f1-48255f4adb42.png)

2023-05-08 18:02 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    private void validateId(long id) {
Рекомендация: Вместо данного метода также можно использовать getUserFromRepositoryOrThrowException, так как они по сути выполняют одну функцию

2023-05-08 18:02 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +        Map<Long, Set<Genre>> filmsGenres = filmGenreStorage.findAllByIds(filmsIds);
Здорово, что все жанры достаются одним запросом!

2023-05-08 18:02 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +public class FilmServiceImpl implements FilmService {
Рекомендация: Вижу, что MPA в фильм сетиться не полностью, а только его идентификатор. Будет лучше если mpa сетить целиком(id + name). Для этого можно использовать join для всех запросов, где достаются фильмы.

2023-05-09 08:24 UTC, dima-irqtsk commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +    private void validateId(long id) {
Сделал, приложение работает, тесты в Постмане проходят, единственное - вылезла куча ошибок в юнит-тесте ЮзерСервиса. Перелопачивать десяток тестов долго, поэтому я откатил эту правку ((

2023-05-09 18:49 UTC, ohelly approved these changes
Привет! Все супер, отлично выполненная работа. Можно двигаться, работу принимаю. Удачи в дальнейшем обучении!

2023-05-10 10:16 UTC, merged